Exception ignored in: <function TreeDB.__del__ at 0x2aaac9f72b70>
Traceback (most recent call last):
  File "/home/cduckworth/scripts/illustris_python/readtreeHDF5.py", line 145, in __del__
  File "/cm/shared/sw/pkg/devel/python3/3.7.3/lib/python3.7/site-packages/h5py/_hl/files.py", line 413, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 37, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
